test: use `t.TempDir` to create temporary test directory
hyperledger/firefly-transaction-manager pull request #75
Opened 2023-04-01 17:38 UTC by Juneezee

This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `t.TempDir` function from the `testing` package to create temporary directory. The directory created by `t.TempDir` is automatically removed when the test and all its subtests complete. 

Reference: https://pkg.go.dev/testing#T.TempDir

```go
func TestFoo(t *testing.T) {
	// before
	dir, err := ioutil.TempDir("", "")
	assert.NoError(t, err)
	defer os.RemoveAll(dir)

	// now
	dir := t.TempDir()
}
```

2023-09-15 20:40 UTC, nguyer requested changes
Hi @Juneezee, sorry for the delay in getting to this review. I'm happy to merge this if you get the failing test fixed. Thanks!

2023-09-16 03:47 UTC, Juneezee commented
Hi @nguyer, thanks for taking the time to review this. I have removed an unused import that was accidentally included in the last rebase. The CI should be fixed now. Please rerun the workflow again. Thanks!

2023-10-06 10:07 UTC, Juneezee commented
@nguyer Friendly ping :smile:

2023-10-24 09:36 UTC, Juneezee commented
@nguyer Friendly ping :smile:

2023-10-25 17:39 UTC, Juneezee commented
@nguyer Friendly ping :smile:

2023-10-27 18:23 UTC, Juneezee commented
@nguyer Friendly ping :smile:

2023-11-01 19:29 UTC, Juneezee commented
@nguyer Friendly ping :smile:

2023-11-06 17:53 UTC, Juneezee commented
@nguyer Friendly ping :smile:

2023-11-08 14:47 UTC, Juneezee commented
@nguyer Friendly ping :smile:

2023-12-28 16:24 UTC, nguyer approved these changes

2023-12-28 16:24 UTC, merged